Repository UBC-MDS/DSCI522_309, pull requests merged in 2020-01, with the labels that each got.

#2 added contributing and Coc
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
Labels: documentation

#14 first rough draft of the proposal
  README.md
Labels: documentation

#16 modified fetch data script using docopt and added a test function
  src/fetch_data.py
Labels: enhancement

#19 changed the format of the citation
  README.md
Labels: enhancement

#20 changed the plot for cat vars and added the team members' names
  README.md
  src/EDA.Rmd
  src/EDA.md
  src/EDA_files/figure-gfm/Target vs Other Variables-2.png
  src/EDA_files/figure-gfm/Target vs Other Variables-3.png
  src/EDA_files/figure-gfm/loading the data-1.png
Labels: documentation, enhancement

#31 finished eda.r
  metric_by_threshold_test.csv
  results/cat_vars_expo.rds
  results/img/cat_vars_dist_plot.png
  results/img/corr_plot.png
  results/img/num_vars_dist_plot.png
  results/quantile_dist.csv
  src/eda.r
Labels: enhancement

#39 modified the documentation of scripts based on TA's suggestions
  src/eda.r
  src/fetch_data.py
  src/pre_process.py
Labels: documentation

#45 added citations file
  doc/citations.bib
Labels: documentation
